[project]
name = "youtube-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-api-python-client>=2.167.0",
    "konlpy>=0.6.0",
]
